<html>
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="css/estilos.css" media="screen" />
		<title>Uso de Librerias y Funciones</title>
	</head>
	<body>
		<?php
			function CabeceraPagina(){
		?>
				<FONT SIZE="+1">Esta cabecera estará en todas sus páginas.</FONT><BR>
				<hr>
		<?php
			}

			function PiePagina(){
		?>
				<hr>
				<FONT SIZE="-1">Este es el pie de página.</FONT><BR>
		<?php
			}
		?>
		<ol>
			<li>¿Que es lo que hace este script?</li>
				<p>Te muestra en pantalla las funciones creadas en la primera pantalla</p>
			<li>¿Cómo creamos una funcion personalizada?</li>
				<p>con function nombreFuncion</p>
			<li>¿Cómo insertamos una funcion?</li>
				<p>include("21_libreria.phtml") </p>
			<li>¿Cómo creamos un archivo de funciones o librería de funciones?</li>
				<p></p>
		</ol>
	</body>
</html>